version: "3"
services:

  api:
    image: api/api
    build: ./api
    container_name: crowsnest-api
    env_file:
      - secret.env
    networks:
      - crowsnest-network
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - "8047:5000"

  db:
    image: db/mysql
    build: ./db
    container_name: crowsnest-db
    env_file:
      - secret.env
    networks:
      - crowsnest-network
    volumes:
      - /mnt/docker-drive/crowsnest/db-data:/var/lib/mysql

volumes:
  db-data:
  web-data:

networks:
   crowsnest-network:
    external: false