version: "3.9"
services:
  api:
    image: api/api
    build: ./api
    volumes:
      - ./api/:/usr/src/app/
    environment:
      - DATABASE_URL=mysql+mysqldb://root:pass@db:3306/test_db #db is name of db host, but points to the local ip
    ports:
      - "8047:5000"
  db:
    image: db/mysql
    build: ./db
    profiles: ["frontend"]
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    ports:
      - "6603:3306"