version: "3.9"
services:
#Disabled - should only be enabled during production
  web:
    image: web/nginx
    build:
      context: "./web"
    volumes:
      - ./web/dist:/usr/share/nginx/html/
    profiles: ["production"]
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
  api:
    image: api/api
    build: ./api
    volumes:
      - ./api/:/usr/src/app/
    environment:
      - DATABASE_URL=mysql+mysqldb://root:pass@db:3306/test_db #db is name of db host, but points to the local ip
    ports:
      - "8000:5000"
  db:
    image: db/mysql
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    ports:
      - "6603:3306"