version: "3.9"
services:
  api:
    image: api/api
    build: ./api
    volumes:
      - ./api/:/usr/src/app/
    environment:
      - DATABASE_URL=mysql+mysqldb://root:${SQL_ROOT_PASS}@db:3306/test_db #db is name of db host, but points to the local ip
      - COOKIE_SECRET=${COOKIE_SECRET}
      - MJ_APIKEY_PUBLIC=${MAIL_APIKEY_PUBLIC}
      - MJ_APIKEY_PRIVATE=${MAIL_APIKEY_PRIVATE}

    ports:
      - "8047:5000"

  db:
    image: db/mysql
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    ports:
      - "6603:3306"